### PR TITLE
chore: e2etests base

### PR DESCRIPTION
**Pull request by Kubessandra**
First draft for testing e2e of the Anima CLI.

- Run CLI on the production cluster with a testing team
- Check if the storybook is ready
- Is using Anima Sample
- Connect with CI

TODO:
- add more testing (design token, stories...)
- Cleaning of teams / stories

### CODE REVIEW

**Review by Datlyfe — CHANGES_REQUESTED** [review]
Can we find a way to prevent adding `storybook-static` to the codebase ?
an idea would be to change `-d` to check if the string is an external URL if so download and extract to a tmp folder

**Comment by orarbel** [comment]
How about accepting -u for url and keeping -d for directory?

Or Arbel
Co-founder | Anima
Tel: +1 (415) 657-6882
My Email ( ***@***.*** ) | My LinkedIn ( https://www.linkedin.com/in/orarbel/ ) | We're Hiring ( https://angel.co/company/anima-app/jobs )
Timezone: Israel

Sent via Superhuman iOS ( ***@***.*** )

**Comment by Kubessandra** [comment]
> Can we find a way to prevent adding storybook-static to the codebase ?
an idea would be to change -d to check if the string is an external URL if so download and extract to a tmp folder

One issue with both solution if I'm not wrong is that if we download only the url it will only download the index.html.
And we need the full content we will need to use something similar to `website-scraper`

**Comment by orarbel** [comment]
For testing purposes the url can be a zip file

Or Arbel
Co-founder | Anima
Tel: +1 (415) 657-6882
My Email ( ***@***.*** ) | My LinkedIn ( https://www.linkedin.com/in/orarbel/ ) | We're Hiring ( https://angel.co/company/anima-app/jobs )
Timezone: Israel

Sent via Superhuman iOS ( ***@***.*** )

**Comment by Datlyfe** [comment]
- The URL used in the test would download a preuploaded sample zip from s3
note:  we can add a ci step in the sample repo later to update that url whenever a push to main happens

**Comment by Kubessandra** [comment]
Ok too bad being able to generate any storybook from his URL could have saved us some time, anyway with the webscraper this not working.

Going with the S3 upload.

**Review by Datlyfe — APPROVED** [review]

**Pull request merged**
